### ISSUE TITLE
No longer works with latest Sinon

### ISSUE THREAD

**Issue by fredricgeorgsson-mobenga** [kmees/karma-sinon-chai#18]
The latest Sinon release has files in a different location and does no longer work with karma-sinon-chai.

Changing package.json from
  "dependencies": {
    "chai": "^1.10",
    "sinon": "^1.12",
    "sinon-chai": "^2.6",
    "lodash": "^2.4.1"
  },

to

  "dependencies": {
    "chai": "^1.10",
    "sinon": "1.12",
    "sinon-chai": "2.6",
    "lodash": "^2.4.1"
  },

and then deleting node_modules dir and running 'npm install' again makes things work again.

**Comment by nfroidure** [comment]
https://github.com/kmees/karma-sinon-chai/pull/17

**Comment by tragiclifestories** [comment]
Honest question as a complete outsider: is there some reason sinon can't be required 'normally', without an explicit call to require.resolve? Having a hard dependency on sinon's directory structure strikes me as a bit brittle. I'm not sure that counts as a part of the public interface for semver purposes.

**Comment by kmees** [comment]
Fixed in Release `0.3.2`

**Comment by kmees** [comment]
@tragiclifestories the npm module of sinon is not meant for usage in a browser (read: karma) which makes requiring it a bit more difficult. Also, changes to the directory structure should probably happen in a major (semver) version upgrade, which they didn't do.

**Comment by tragiclifestories** [comment]
I see. Thanks for the explanation.

Looks like it was unintentional anyway: https://github.com/cjohansen/Sinon.JS/issues/761#issuecomment-110678243

**Comment by mziwisky** [comment]
https://github.com/cjohansen/Sinon.JS/issues/761 is allegedly fixed w/ v1.15.3, but i'm still having issues that i believe are related to it.  i include karma-sinon-chai v1.0.0, which pulls in the following dependencies:

```
karma-sinon-chai@1.0.0 node_modules/karma-sinon-chai
├── sinon-chai@2.8.0
├── chai@3.0.0 (assertion-error@1.0.1, type-detect@1.0.0, deep-eql@0.1.3)
├── lodash@2.4.2
└── sinon@1.15.3 (formatio@1.1.1, samsam@1.1.2, lolex@1.1.0, util@0.10.3)
```

and in the beginning of my test suite, i call `sinon.useFakeTimers()`, but i'm getting `TypeError: sinon.useFakeTimers is not a function`

when i stick a debugger in there, i do see that `sinon` exists, and has the usual methods like `stub` and `spy`, but `sinon.useFakeTimers` is undefined.
